export const COUNTRIES = [
  { code: '', name: 'No especificada' },
  { code: 'ar', name: 'Argentina' },
  { code: 'bo', name: 'Bolivia' },
  { code: 'br', name: 'Brasil' },
  { code: 'cl', name: 'Chile' },
  { code: 'co', name: 'Colombia' },
  { code: 'cr', name: 'Costa Rica' },
  { code: 'cu', name: 'Cuba' },
  { code: 'ec', name: 'Ecuador' },
  { code: 'sv', name: 'El Salvador' },
  { code: 'gt', name: 'Guatemala' },
  { code: 'hn', name: 'Honduras' },
  { code: 'mx', name: 'México' },
  { code: 'ni', name: 'Nicaragua' },
  { code: 'pa', name: 'Panamá' },
  { code: 'py', name: 'Paraguay' },
  { code: 'pe', name: 'Perú' },
  { code: 'pr', name: 'Puerto Rico' },
  { code: 'do', name: 'República Dominicana' },
  { code: 'uy', name: 'Uruguay' },
  { code: 've', name: 'Venezuela' },
  { code: 'us', name: 'Estados Unidos' },
  { code: 'ca', name: 'Canadá' },
  { code: 'es', name: 'España' },
  { code: 'de', name: 'Alemania' },
  { code: 'fr', name: 'Francia' },
  { code: 'it', name: 'Italia' },
  { code: 'gb', name: 'Reino Unido' },
  { code: 'pt', name: 'Portugal' },
  { code: 'nl', name: 'Países Bajos' },
  { code: 'be', name: 'Bélgica' },
  { code: 'ch', name: 'Suiza' },
  { code: 'at', name: 'Austria' },
  { code: 'se', name: 'Suecia' },
  { code: 'no', name: 'Noruega' },
  { code: 'dk', name: 'Dinamarca' },
  { code: 'fi', name: 'Finlandia' },
  { code: 'ru', name: 'Rusia' },
  { code: 'ua', name: 'Ucrania' },
  { code: 'pl', name: 'Polonia' },
  { code: 'cz', name: 'República Checa' },
  { code: 'sk', name: 'Eslovaquia' },
  { code: 'rs', name: 'Serbia' },
  { code: 'hr', name: 'Croacia' },
  { code: 'ro', name: 'Rumania' },
  { code: 'bg', name: 'Bulgaria' },
  { code: 'gr', name: 'Grecia' },
  { code: 'tr', name: 'Turquía' },
  { code: 'au', name: 'Australia' },
  { code: 'nz', name: 'Nueva Zelanda' },
  { code: 'jp', name: 'Japón' },
  { code: 'cn', name: 'China' },
  { code: 'kr', name: 'Corea del Sur' },
  { code: 'in', name: 'India' },
  { code: 'id', name: 'Indonesia' },
  { code: 'th', name: 'Tailandia' },
  { code: 'vn', name: 'Vietnam' },
  { code: 'ph', name: 'Filipinas' },
  { code: 'my', name: 'Malasia' },
  { code: 'sg', name: 'Singapur' },
  { code: 'tw', name: 'Taiwán' },
  { code: 'za', name: 'Sudáfrica' },
  { code: 'eg', name: 'Egipto' },
  { code: 'ma', name: 'Marruecos' },
  { code: 'dz', name: 'Argelia' },
  { code: 'ng', name: 'Nigeria' },
  { code: 'il', name: 'Israel' },
  { code: 'sa', name: 'Arabia Saudita' },
  { code: 'ae', name: 'Emiratos Árabes Unidos' }
];
